name: End-to-End Tests

on:
  push:
    branches: [ main]
  pull_request:
    branches: [ main]

jobs:
  e2e-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run migrations
      run: npm run migration:clean && npm run migration:run
    
    - name: Run e2e tests
      run: npm run test:e2e
